### ISSUE TITLE
README might need updating

### ISSUE THREAD

**Issue by matthiaslein** [KristapsE/DP4-AI#1]
I've recently tried to use PyDP4 and I could't get it to run. One problem I've encountered is the fact that the options described in the README are different from the options presented by PyDP4 --help.

Would it be possible to describe a workflow for the case that I have (Gaussian) DFT NMR files already and would just like to run the DP4 analysis on those data?

Thanks a lot!

**Comment by KristapsE** [comment]
Unfortunately the readme is definitely a bit out of date at the moment - I'll try to update it in the next few weeks before the term starts.

The general command in your case would be something like this:
PyDP4.py -s chloroform -F mPW1PW91 -B '6-311g(d)' -d g --AssumeDFTDone structure1 structure2 ... StructureNMR

where -s argument defines the solvent, -F defines the functional, -B defines the basis set used, and -d g defines that the DFT was done with Gaussian.
--AssumeDFTDone switch is useful in your case to ask PyDP4 not to look for conformational search files and not to try and generate new Gaussian inputs. After this then follows 2 or more isomer structure (base) filenames. For the PyDP4 to find the DFT files, the actual files should follow the form structure1ginp001.out for the first conformer of the first isomer, structure1ginp002.out for the 2nd conformer of the first isomer, structure2ginp001.out for the 1st conformer of the second isomer and so forth. structure1 and structure2 can be replaced with any other, nonrelated file names, as long as the DFT files follow a similar scheme.

We have uploaded all of the input and output files from the latest paper to Cambridge repository here:
https://www.repository.cam.ac.uk/handle/1810/267217
The whole archive is quite large, but it may be useful as test data.

Hope this helps!
