### ISSUE TITLE
Boost.Python.Argument.Error

### ISSUE THREAD

**Issue by darose93** [KristapsE/DP4-AI#11]
I am currently attempting to run this program on a Mac and have been able to open up the GUI, however, once I input the files and start the calculations python will immediately crash.  The error code below was displayed so I updated my boost package to boost-1.67.0-py37_4 however this did not appear to have any effect. 

`Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdinchi.MolToInchi(NoneType, str)
did not match C++ signature:
    MolToInchi(RDKit::ROMol mol, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > options='')`

I have minimal experience working with python so any insight into this issue would be really appreciated.

**Comment by HowarthA** [comment]
Hi,
Despite being developed and tested most extensively on Linux, DP4-AI will run on a macOS. What version of rdkit do you have installed? The inchi generation code is running smoothly on my Mac (OS Mojave) using Python 3.7 and rdkit version 2019.09.3.0.

**Comment by darose93** [comment]
Hi,
I am also running Mac (OS Mojave) using Python 3.7 with the rdkit
version rdkit-2020.03.1.0.  I later realized that issue was related to the
.sdf file format.  For some reason, my exported file had the incorrect
heading/formatting which once I fixed that issue did go away.  I then ran
into another problem moments later dealing with the sdf2tinker executable.
I have copied the error message below.

Setting up Tinker files...

/bin/sh: /Applications/DP4-AI-master/sdf2tinkerxyz: cannot execute binary
file

Traceback (most recent call last):

  File "PyDP4_GUI.py", line 2001, in runPyDP4

    self.NMRData, self.Isomers, self.settings, self.DP4Data =
PyDP4.main(ui.table_widget.Tab1.settings)

  File "/Applications/DP4-AI-master/PyDP4.py", line 210, in main

    TinkerInputs = Tinker.SetupTinker(settings)

  File "/Applications/DP4-AI-master/Tinker.py", line 54, in SetupTinker

    outp = subprocess.check_output(convinp + inpf + '.sdf', shell=True)

  File "/Users/newuser/opt/anaconda3/lib/python3.7/subprocess.py", line
411, in check_output

    **kwargs).stdout

  File "/Users/newuser/opt/anaconda3/lib/python3.7/subprocess.py", line
512, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command
'/Applications/DP4-AI-master/sdf2tinkerxyz -k
/Applications/DP4-AI-master/default.key <BYH1_new1.sdf' returned non-zero
exit status 126.

Abort trap: 6


I attempted to redownload the executable but that ultimately led to the
same error message.


I really appreciate your help with this!

Doug Rose

**Comment by KristapsE** [comment]
sdf2tinkerxyz is a Linux binary that converts the sdf file to tinker xyz format, so the problem in hindsight is not unexpected. TINKER on Mac OS is definitely a combination we haven't tried yet.

You should try downloading the Mac OS binary for sdf2tinkerxyz copy it over the file you downloaded from the GitHub.

http://sdf2xyz2sdf.sourceforge.net/?Downloads

**Comment by KristapsE** [comment]
I assume that this fixed the issue, so I will close this issue now.
