### ISSUE TITLE
What type of file should I import？Can you give some examples？

### ISSUE THREAD

**Issue by youngbee12** [KristapsE/DP4-AI#17]
![图片](https://user-images.githubusercontent.com/61130599/80814555-ae460580-8bfe-11ea-8fa2-e44230fb41ef.png)

**Comment by KristapsE** [comment]
All of the files used in the study in the arrangement fit for running DP4-AI have been released on the Cambridge repository here:

https://www.repository.cam.ac.uk/handle/1810/303161

I would suggest you download a few of these, they should give you a better idea of what the input data is expected. Structures are expected to be in sdf format. Generally either several structure candidates, or one candidate in combination with automatic diastereomer generation is used. NMR can be either NMR description or a Bruker raw NMR data folder (examples of both are available in the link above in the compound folders).

**Comment by kkBecky** [comment]
I download some folders from the link you provide, but only the sdf format can be added in"structure", no other files can be added in "NMR", I am wondering that what kind of NMR data can be added, usually I use Mestrenova to get the NMR data and output  data to Word. thank you
