### ISSUE TITLE
could you tell me more details about what type of folders can be added?

### ISSUE THREAD

**Issue by kkBecky** [KristapsE/DP4-AI#20]
I download some folders from the link https://www.repository.cam.ac.uk/handle/1810/303161 you provide, but only the sdf format can be added in"structure", no other files can be added in "NMR", I am wondering that what kind of NMR data can be added, usually I use Mestrenova to get the NMR data and output data to Word. thank you

**Comment by renzilin** [comment]
The link is https://www.repository.cam.ac.uk/handle/1810/303161

**Comment by KristapsE** [comment]
Structure expects you add your structure candidates - what structures do you want DP4 to distinguish between?

NMR field expects you to add NMR data - either NMR descriptions in the format expected by the DP4, or in the form of a Bruker folder, containing raw carbon and proton NMR data. Examples of both are in each of the folders in the Cambridge repository dataset.

**Comment by kkBecky** [comment]
First , I want to confirm the structure.I put my data in the Spectral Database to analyze. I only got a cerebroside-type  compound with a similarity rate of 73%. I want to know whether the structure of the compound can be determined by DP4.

When I try to use your software, I downloaded the KE1 file from the link [Cambridge repository dataset](https://www.repository.cam.ac.uk/handle/1810/303161), added the sdf file⁨ KE1⁩/Opt_E⁩/KE1_3.sdf & KE1⁩/Opt_E⁩/KE1_4.sdf (picture1) in the "structure", and no file could be added in the "NMR "(picture2), so I had to add the carbon and proton folders KE1/Opt_E/NMR_folder/Carbon & KE1/Opt_E/NMR_folder/Proton. After adding the output folder and click to "calculate", the program reports an error (picture3)
This is the problem I met, I hope you can give me some suggestions, thank you!

<img width="928" alt="picture1" src="https://user-images.githubusercontent.com/64761425/81072097-3aff0500-8f18-11ea-8dcd-0696d5472f1f.png">
<img width="946" alt="picture2" src="https://user-images.githubusercontent.com/64761425/81072087-36d2e780-8f18-11ea-9241-b271fb106b65.png">
<img width="1440" alt="picture3" src="https://user-images.githubusercontent.com/64761425/81072105-3e928c00-8f18-11ea-9fef-1fef4985789a.png">

**Comment by KristapsE** [comment]
Do you have MacroModel installed? The script seems to tell you that you don't have a molecular mechanics software installed or that it doesn't know where it is installed. DP4-AI requires either TINKER or MacroModel to function properly on new compounds.

The GUI should still give you an answer for already calculated compounds, so maybe Alex will chip in about why it is still looking for MacroModel on our data.

**Comment by kkBecky** [comment]
Thanks for your reply! I will download the MacroModel to see if it works!!

**Comment by KristapsE** [comment]
MacroModel is a commercial package, if you don't have access to a license already, it would be quite expensive to acquire it. For running new analysis, open-source TINKER may be a financially more realistic option. Running DP4-AI on existing computational data shouldn't require any additional software - we are looking into why this is not the case.

**Comment by kkBecky** [comment]
Thank you for your reminding! I did have trouble installing the MacroModel, and I am now trying to install Tinker,  I have limited knowledge in computer chemistry, so it will take some time. Thank you for your answer! I will try if DP4 works after installing Tinker!!

**Comment by kkBecky** [comment]
I have already installed Tinker, but still reports an error(picture)
thank you!!


<img width="1440" alt="picture 2020-05-06 20 39 48" src="https://user-images.githubusercontent.com/64761425/81178240-7eba4300-8fda-11ea-88c4-f9088e082133.png">

**Comment by HowarthA** [comment]
Hi, a little note about passing the NMR data. At the moment DP4-AI is expecting you to give it a single folder containing the carbon and proton data as subfolders, in the case of KE3 it wants the whole "NMR_folder". I wonder whether giving it the proton and carbon data separately has lead to some additional files being generated with odd file extensions, this might be why it no longer likes KE3_4.sdf. Try starting with a new copy of the KE3 folder. Something else that may be causing it to trip up is requesting diastereomer generation whilst passing multiple structures, try deselecting this toggle switch. Hope this helps.

**Comment by kkBecky** [comment]
Hi, I tried again according to your suggestion. No matter if I add one or more sdf files to the “structure”, the same error still occurs(picture). I am wondering if it is because the full directory of the JB2_4.sdf can not be added in your software. Thank you!!
<img width="936" alt="picture1 2020-05-06 23 12 59" src="https://user-images.githubusercontent.com/64761425/81196691-f0ea5200-8ff1-11ea-8233-b995211559ca.png">
<img width="1440" alt="picture2 2020-05-06 23 18 57" src="https://user-images.githubusercontent.com/64761425/81197186-8f76b300-8ff2-11ea-85bc-7f5ebc9f3c32.png">

**Comment by KristapsE** [comment]
Did you launch the GUI from the folder where your data is, or from the DP4-AI folder?

**Comment by youngbee12** [comment]
I don't know why this happens
![图片](https://user-images.githubusercontent.com/61130599/81277177-a23ac780-9086-11ea-8fc4-ec0850500c8b.png)

**Comment by KristapsE** [comment]
@youngbee12 this looks like a separate issue - would you mind opening a new issue? Thanks.

**Comment by kkBecky** [comment]
I launched the GUI from the folder where my  data was before. Should I remove the data to the DP4-AI folder? I just try it but still the same error occurs
thanks

<img width="1440" alt="picture 2020-05-07 18 53 44" src="https://user-images.githubusercontent.com/64761425/81287229-006ea700-9095-11ea-9d8f-aaf1044baebd.png">

**Comment by KristapsE** [comment]
Thank you for your patience! I am working on this issue right now, there should be an improved version tomorrow morning. Yes, moving the data to the DP4-AI folder should work, but it's not very user friendly, so I am working on a fix.

**Comment by HowarthA** [comment]
Hi, just to chip in. We are very close to an improved file input system so all of these problems will be fixed very soon. If you download the JB2 folder from the repository, you will want to change to the "MM" subdirectory within this folder before running the GUI i.e first run the command "cd /your path here/JB2/MM" then "python /path to pydp4/PyDP4_GUI.py". Next add JB2_4.sdf to the structure dialogue and the whole "NMR_folder" to the NMR dialogue. Click the "NMR assignment" checkbox and then **make sure to uncheck the generate diastereomers checkbox** finally hit Calculate. Hopefully this will get you up and running before trying out Tinker. Hope this helps!

**Comment by kkBecky** [comment]
Hi, I used your latest script and follow your instructions to run the calculation, but still the error occurs.

<img width="571" alt="屏幕快照 2020-05-08 09 25 03" src="https://user-images.githubusercontent.com/64761425/81361100-11103300-9110-11ea-8cbd-dddc363cebbd.png">

**Comment by renzilin** [comment]
Dear Authors,
I thouht that I have the same problems on my ubuntu 16.04.
I used conda & pip to create the enviroment.
And as your instructions, I `cd` to the JB2 folder and started the GUI script.
![image](https://user-images.githubusercontent.com/17135904/81369404-5147c500-90c0-11ea-8c09-f35c62fe37cf.png)

And then I followed your instruction to choose the file `JB2_4.sdf` and folders `NMR_folder`. Press `Calculate`.
![image](https://user-images.githubusercontent.com/17135904/81369545-b7344c80-90c0-11ea-9c1a-51aa1e40714b.png)

Here's the return with error.
![image](https://user-images.githubusercontent.com/17135904/81369666-fc587e80-90c0-11ea-8a84-7e06c3466bb1.png)

Thank your for your help.

**Comment by KristapsE** [comment]
Hi @kkBecky  and @renzilin! We have just pushed a new update which significantly improves the path logic behind the GUI, so please download the latest source code and copy it over and let us know how it goes!
Just as a reminder - in the Add structure please add all of the diastereomers in the folder (JB1_1.sdf, JB1_2.sdf etc, but not JB_.sdf), in the NMR folder add the corresponding NMR data folder and in the output folder add the whole top level folder containing both the sdf files and the NMR data. Please don't use Generate diastereomers option if you provide more than one structure.

**Comment by kkBecky** [comment]
Hi, thanks for your help but there is still something wrong. I used your latest script just then, and follow your instructions. Add Downloads/JB2/MM/JB2_2.sdf and Downloads/JB2/MM/JB2_4.sdf. in "structure", add Downloads/JB2/MM/NMR_folder in "NMR", add add Downloads/JB2/MM in "output" (picture1), but there is still error occurs(picture2)
thank you!!

<img width="934" alt="picture1 2020-05-08 22 12 15" src="https://user-images.githubusercontent.com/64761425/81414826-2326bb80-917a-11ea-9425-3496ea0f61f0.png">
<img width="1437" alt="picture2 2020-05-08 22 13 05" src="https://user-images.githubusercontent.com/64761425/81414965-5a956800-917a-11ea-891e-47377c22ce41.png">

**Comment by KristapsE** [comment]
When trying to run our data, you should select MacroModel, not Tinker, as we used MacroModel for our workflows.

For your own process, you will need to select TINKER for Molecular Mechanics. And we will need to add options in the GUI for using NWChem. Also there will be a need for some modifications in the script specifically for your situation that you will need to make to ensure script knows where your TINKER and NWChem lives.

**Comment by renzilin** [comment]
> When trying to run our data, you should select MacroModel, not Tinker, as we used MacroModel for our workflows.
> 
> For your own process, you will need to select TINKER for Molecular Mechanics. And we will need to add options in the GUI for using NWChem. Also there will be a need for some modifications in the script specifically for your situation that you will need to make to ensure script knows where your TINKER and NWChem lives.

Okay, thanks for your quick reply. 
I re-read your intro, I think the tinker and NWChem is both need, I'll try it with our own data. 

Thank you.

**Comment by KristapsE** [comment]
Hi @renzilin and @kkBecky ! I had a chance to do some coding today and implemented a separate config file - settings.cfg. This meant as an easier way to let DP4-AI know where to find the molecular mechanics (TINKER or MacroModel) and the DFT (Gaussian or NWChem) packages. A sample settings.cfg file is provided in the latest update - feel free to download the latest version, test it and let us know how it does!

**Comment by renzilin** [comment]
> Hi @renzilin and @kkBecky ! I had a chance to do some coding today and implemented a separate config file - settings.cfg. This meant as an easier way to let DP4-AI know where to find the molecular mechanics (TINKER or MacroModel) and the DFT (Gaussian or NWChem) packages. A sample settings.cfg file is provided in the latest update - feel free to download the latest version, test it and let us know how it does!

Hi @KristapsE !
Could you please explain what is the sdf2tinkerxyz? It can't work when we used tinker to do analysis.
The same mistake:
![Annotation 2020-05-10 000210](https://user-images.githubusercontent.com/17135904/81490527-88011500-9251-11ea-89c8-11b3b308e2a5.png)

**Comment by KristapsE** [comment]
It's a utility that converts from sdf to TINKER custom xyz format. There are binaries for all three major platforms available from this website, as well as the source code.

http://sdf2xyz2sdf.sourceforge.net/?Description:sdf2tinkerxyz

**Comment by KristapsE** [comment]
I think this particular issue about folders in the GUI have been solved, so I will close this now.
