### ISSUE TITLE
NWChem no jobs to run

### ISSUE THREAD

**Issue by AmonB** [KristapsE/DP4-AI#21]
I would like to know how to fix this problem.  
Running NWChem DFT NMR calculations locally...
There were no jobs to run.
 I've install NWchem, TINKER. Did I miss something?

![image](https://user-images.githubusercontent.com/64903539/81176810-49145a80-8fd8-11ea-969c-6e4b2652eef9.png)

**Comment by KristapsE** [comment]
Could you please post the initial command you used to launch the workflow? It doesn't look like the workflow was given any structure files to analyze...

**Comment by AmonB** [comment]
![image](https://user-images.githubusercontent.com/64903539/81178864-6c8cd480-8fdb-11ea-8a4c-eebdac7bc754.png)
![image](https://user-images.githubusercontent.com/64903539/81179026-a958cb80-8fdb-11ea-9ad3-5e979516539f.png)
I wonder my NWchem didn't work or there is something I miss in the PyDP4.py

**Comment by KristapsE** [comment]
You need to provide 3D structure candidates for the NMR spectra analysis to work - you should add them in the add structure box.

**Comment by AmonB** [comment]
Thank you, I added two .sdf but now I have another problem.  
![image](https://user-images.githubusercontent.com/64903539/81185512-41f34980-8fe4-11ea-9e88-0a83fef1f3a8.png)

![image](https://user-images.githubusercontent.com/64903539/81184996-a19d2500-8fe3-11ea-9434-2844b2176d42.png)
I have added the path in the Tinker.py 
![image](https://user-images.githubusercontent.com/64903539/81185382-18d2b900-8fe4-11ea-8c8d-228629fe70eb.png)

**Comment by KristapsE** [comment]
Could you please download the most recent source version? I think this is the issue in the GUI where you need to launch it from the folder where your input files are, otherwise it won't find them. We have done some bugfixing in the last two weeks, which may have fixed this issue as well. If not, then please for the time being launch the GUI from the folder containing your input files. The command line version does not have this issue.

**Comment by AmonB** [comment]
Thank you for your excellent project. I'm looking forward to the better version. And I wonder there will have the demo .py files that highlight where should be change in the next version, because there will be many tricky errors if the settings are wrong.

**Comment by KristapsE** [comment]
Ideally there would be a configuration script that fills in a config file, which is then read by PyDP4.py and PyDP4_GUI.py scripts on startup. Certainly on the TODO list - just like many other things!

**Comment by HowarthA** [comment]
Hi, AmonB thanks for getting in touch. I've noticed you're currently not giving DP4-AI the NMR data in quite the way it is expecting. At the moment DP4-AI wants to be given a single folder containing one/two subfolders, one named "Proton" containing the Proton NMR data and one called "Carbon" containing the carbon NMR data. Have a look at one of the files in the repository if you are still unsure https://doi.org/10.17863/CAM.47721 This being said we are currently testing a new file input system which will make all of this much easier, hope this helps!

**Comment by KristapsE** [comment]
Hi @AmonB! I had a chance to do some coding today and implemented a separate config file - settings.cfg. This meant as an easier way to let DP4-AI know where to find the molecular mechanics (TINKER or MacroModel) and the DFT (Gaussian or NWChem) packages. A sample settings.cfg file is provided in the latest update - feel free to download the latest version, test it and let us know how it does!

**Comment by KristapsE** [comment]
So we have made several improvements over the last week, the latest version shouldn't have these issues. If they persist, please open a new issue, but I am going to close this one.
