### ISSUE TITLE
bmin returned non-zero exit status 126

### ISSUE THREAD

**Issue by youngbee12** [KristapsE/DP4-AI#22]
![图片](https://user-images.githubusercontent.com/61130599/81278722-a49e2100-9088-11ea-8d34-7522030be5c4.png)

**Comment by KristapsE** [comment]
It looks like DP4 is trying to launch MacroModel bmin executable, but can't do that because of insufficient file permissions. Please try launching it manually in a new terminal with '/media/young_bee123/AnGEL/schor/bmin AT1_1'

If it doesn't work, then either your user is not allowed to access the file, or perhaps the bmin is not allowed to be executed. This can be fixed with running "chmod +x bmin" in the schrodinger folder

**Comment by youngbee12** [comment]
Thanks for your advice.But i can't find a file called bmin.I change bmin into maestro,then it runs maestro.After that I don’t know what to do.
![图片](https://user-images.githubusercontent.com/61130599/81295276-c2787f80-90a2-11ea-81f7-b02de3e9f176.png)
![图片](https://user-images.githubusercontent.com/61130599/81295293-c86e6080-90a2-11ea-8127-21a6b7232caa.png)
![图片](https://user-images.githubusercontent.com/61130599/81295497-14210a00-90a3-11ea-8b24-89fe267382b9.png)

**Comment by KristapsE** [comment]
What I meant is - can you find the bmin executable in your schrodinger folder? If it's there you should be able to launch it manually from command line, if your user and the file have the right permissions.

**Comment by youngbee12** [comment]
I can't find bmin executable in my schrodinger folder....

**Comment by KristapsE** [comment]
That would suggest to me that you don't have MacroModel installed. Do you have the free Maestro version, or the full commercial Schrodinger Suite? MacroModel is included only in the paid Schrodinger Suite.

The DP4-AI will not work without either MacroModel or TINKER as the molecular mechanics software.

**Comment by youngbee12** [comment]
Ok i will buy one，thanks for your help

**Comment by youngbee12** [comment]
what does“returned non-zero exit status 1”mean？
![图片](https://user-images.githubusercontent.com/61130599/81362590-c690b580-9113-11ea-98ac-c4ad7338b4af.png)

**Comment by KristapsE** [comment]
Still seems to be a problem with your MacroModel. Have you tried running bmin manually from command line? The output files might contain some error messages.

**Comment by youngbee12** [comment]
Cannot open shared object file, but I found this file (libxxxx.so)in another directory.
![图片](https://user-images.githubusercontent.com/61130599/81460114-bfca7700-91d5-11ea-803f-a61118c56e30.png)

**Comment by KristapsE** [comment]
That is definitely a problem with your Schrodinger installation. Maybe try looking into this GitHub which seems relevant? 
https://github.com/schrodinger/coordgenlibs

Also could try installing this package, or it's ubuntu analog.
https://packages.debian.org/sid/libschroedinger-coordgenlibs1

**Comment by WeiYongqiang55** [comment]
> what does“returned non-zero exit status 1”mean？
> ![图片](https://user-images.githubusercontent.com/61130599/81362590-c690b580-9113-11ea-98ac-c4ad7338b4af.png)

I met same problem, do you solved this problem?could you please tell how ? thank you so much

**Comment by WeiYongqiang55** [comment]
> Cannot open shared object file, but I found this file (libxxxx.so)in another directory.
> ![图片](https://user-images.githubusercontent.com/61130599/81460114-bfca7700-91d5-11ea-803f-a61118c56e30.png)

I have bmin  & could could run it
(chem-env) root@ubuntu:/app/schrodinger2018-1# ./bmin

Usage: bmin <jobname> [OtherOptions] [JobOptions] [DiagnosticOptions]

  <jobname>            The name of the .com file leaving out the ".com".
                       Not needed or used if -TEST or -HELP are specified.

  Other Options:
  --------------
     -h, -help, -HELP  Print this message and exit.

     -DEBUGGER  <debugger_name>
                       Run bmin in the foreground with specified debugger.

     -TEST             Run the standard test suite (jobname not needed).
     -DEV_TEST         Run the developers version of the standard test suite
                       (jobname not needed). Turns on -TEST.

  Job Options:
  ------------
     -DEBUG            Show details of operation of the toplevel scripts.

     -HOST <hostname> or
     -HOST <hostname:nproc> or
     -HOST "hostname1:nproc1 hostname2:nproc2 ... hostnameN:nprocN"
                       Distribute the job over the specified hosts. The driver
                       job is run on the first host specified. If -SUBHOST is
                       used to specify the hosts for the subjobs, the -HOST
                       option only specifies the host for the driver.

     -HOSTFILE <host_file_name>
                       The name of the host file to use for this run.

     -LOCAL            Do not use a temporary directory for job files.
                       Keep files in the launch directory.

     -NICE             Run the job at reduced priority.

     -NOJOBID          Do not use job control and print bmin messages to the
                       screen.

     -PROJ <name>      Assign job to a Maestro project <name>.

     -TMPDIR <directory>
                       The name of the directory used to store files
                       temporarily during a job.

     -USER <name>      Launch job as user <name>.

     -WAIT             Do not return a prompt until the job completes.

     -RESTART          Restart the previously failed parent job.
                       This facility works only for local jobs.

     -ARCH <pattern>   The platform tag must match <pattern> (e.g. mips3).

     -COMPAT <dir>     Require compatiblity with executables in <exec_dir>.

     -REL <vernum>     The version number must match <vernum>
                       (e.g. 80 or 80015).

     -VER <pattern>    Exec directory pathname must match <pattern>.

   ** Distributed job options:
     -SUBHOST <hostname> or
     -SUBHOST <hostname:nproc> or
     -SUBHOST "hostname1:nproc1 hostname2:nproc2 ... hostnameN:nprocN"
                       Run the subjobs on the specified hosts.
                       The driver is run on the host specified with -HOST.

     -NJOBS <number>   Number of subjobs to create.
                       If this option is omitted, -NJOBS will be set to the
                       number of cpus requested with -SUBHOST option.

     -JOBCTS <number>  Ensure that each subjob has no more than this many
                       structures to process. Defaults to 10000.

     -STRICT_END       Terminate if any of the subjobs dies.

     -MAX_RETRIES      Number of allowed retries per subjob.

     -first            First structure to process.

     -last             Last structure to process.

     -OUTPUT_ORG <option>
                       Produce more than one output structure file.
                       If option is BY_SUBJOB produce one output file for each
                       subjob. Otherwise create a new directory called: option
                       and create separate output files for each input ligand
                       within this new directory.

     -NC or -nc        Do not clean up by removing intermediate files.
                       By default many intermediate job files are removed.

     -nx               Do not run jobs, but create specified subjob directories
                       and input structures.

     -j <range_values> Only run specified subjobs.
                       For example of range values;
                        10           job number 10
                        1:15         job numbers 1 to 15
                        "1, 5, 10"   job numbers 1, 5, and 10
                        "1:15, 18"   job numbers 1 to 15 and 18
                        "1:5, 15:20" job numbers 1 to 15 and 15 to 20

  Diagnostic Options: (Provide information but the program will not run).
  -------------------
     -ALL              Ignore platform compatibility (list all platforms).
     -ENTRY            List the relevant host entry(s) from the hosts file.
     -HOSTS            List the hosts available for remote jobs.
     -LIST             List all the platform-compatible versions of product.
     -WHICH            Report the product exec directory and MMSHARE_EXEC.
     -WHY              Show details of how the selected exec dir was chosen.
    
(chem-env) root@ubuntu:/app/schrodinger2018-1#

**Comment by KristapsE** [comment]
Are you running the latest version of DP4-AI? The latest update was released just 2 days ago, which have introduced some improvements in file location specification, both for executables and the input files. Could you please paste the output from DP4-AI? Your bmin installation looks fine, so it must be a file location issue, but difficult to say anything more specific without the error messages.

**Comment by youngbee12** [comment]
My computer is paralyzed, so I am still recovering my data.Thank you for helping me solve the problem，I will try later1

**Comment by youngbee12** [comment]
> 
> 
> > what does“returned non-zero exit status 1”mean？
> > ![图片](https://user-images.githubusercontent.com/61130599/81362590-c690b580-9113-11ea-98ac-c4ad7338b4af.png)
> 
> I met same problem, do you solved this problem?could you please tell how ? thank you so much

Sorry i haven't solved

**Comment by WeiYongqiang55** [comment]
> Are you running the latest version of DP4-AI? The latest update was released just 2 days ago, which have introduced some improvements in file location specification, both for executables and the input files. Could you please paste the output from DP4-AI? Your bmin installation looks fine, so it must be a file location issue, but difficult to say anything more specific without the error messages.

>I try the new code ,and met some other bug,I open a new issue,could you please have a look ?thank you

**Comment by WeiYongqiang55** [comment]
> Are you running the latest version of DP4-AI? The latest update was released just 2 days ago, which have introduced some improvements in file location specification, both for executables and the input files. Could you please paste the output from DP4-AI? Your bmin installation looks fine, so it must be a file location issue, but difficult to say anything more specific without the error messages.

well  I use old code DP4, output is exectly seem  with https://user-images.githubusercontent.com/61130599/81362590-c690b580-9113-11ea-98ac-c4ad7338b4af.png

**Comment by KristapsE** [comment]
I would probably try reinstalling Schrodinger and see if you can run bmin manually from either command line or the Maestro interface. But as it seems as an issue with MacroModel, and not with DP4-AI, I am going to close this issue.
