### ISSUE TITLE
g16 returned non-zero exit status 139

### ISSUE THREAD

**Issue by WeiYongqiang55** [KristapsE/DP4-AI#23]
/DP4-AI-master# python PyDP4_GUI.py 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QLayout: Attempting to add QLayout "" to TabWidget "", which already has a layout
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Initial input files: ['R-3dstructure.sdf']
NMR file: shouxingputu
Workflow: gmo

Generating diastereomers...
Getting inchi from file  R-3dstructure.sdf
Getting inchi from file  R-3dstructure.sdf
Number of diastereomers to be generated: 1
Isomer 0 inchi = InChI=1S/C16H20O/c1-16(11-13-7-3-2-4-8-13)12-17-15-10-6-5-9-14(15)16/h5-7,9-10H,2-4,8,11-12H2,1H3/t16-/m0/s1/f/
Generated input files: ['R-3dstructure1']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using MacroModel

Setting up MacroModel files...
Macromodel input for R-3dstructure1 prepared.
MacroModel inputs: ['R-3dstructure1.mae']
Running MacroModel...
Valid R-3dstructure1.log exists, skipping...

Reading conformers...
R-3dstructure1.log is matching conformational search output for R-3dstructure1
Energy window: 10.0 kJ/mol
R-3dstructure1: 22 conformers read within energy window

Pruning conformers...
R-3dstructure1: 22 conformers after pruning with 0A RMSD cutoff

Setting up geometry optimization calculations...

Running geometry optimization calculations...

Running Gaussian DFT geometry optimizations locally...
/root/opt/gaussian/g16/g16< R-3dstructure1ginp012.com > R-3dstructure1ginp012.out
No executable for file l1.exe.

Search path GAUSS_EXEDIR is "/root/opt/gaussian/g16"
: No such file or directory
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "PyDP4_GUI.py", line 2002, in runPyDP4
    self.NMRData, self.Isomers, self.settings, self.DP4Data = PyDP4.main(ui.table_widget.Tab1.settings)
  File "/home/wyq/Downloads/DP4-AI-master/PyDP4.py", line 258, in main
    Isomers = DFT.RunOptCalcs(Isomers, settings)
  File "/home/wyq/Downloads/DP4-AI-master/Gaussian.py", line 254, in RunOptCalcs
    Completed = RunCalcs(GausJobs)
  File "/home/wyq/Downloads/DP4-AI-master/Gaussian.py", line 295, in RunCalcs
    outp = subprocess.check_output(GausPrefix + f + ' > ' + f[:-3] + 'out', shell=True)
  File "/home/wyq/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/wyq/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/root/opt/gaussian/g16/g16< R-3dstructure1ginp012.com > R-3dstructure1ginp012.out' returned non-zero exit status 139.
已放弃 (核心已转储)

**Comment by KristapsE** [comment]
That folder will require root permissions to access. Do you launch DP4-AI with root permissions? The Gaussian program cannot find l1.exe - does this exist?

You could also try executing the printed command manually in a terminal in the same environment as the script, to check if it works:
/root/opt/gaussian/g16/g16< R-3dstructure1ginp012.com > R-3dstructure1ginp012.out
If it doesn't, it probably isn't a problem with the script, but with your environment and/or the provided path.

**Comment by WeiYongqiang55** [comment]
yes

**Comment by WeiYongqiang55** [comment]
I  use root run PyDp4_GUI.py and there are l1.exe in /root/opt/gaussian/g16/ ,
I try what u said and I got 

root@ubuntu:~/opt/gaussian# /root/opt/gaussian/g16/g16< R-3dstructure1ginp012.com > R-3dstructure1ginp012.out
-bash: R-3dstructure1ginp012.com: 没有那个文件或目录
root@ubuntu:~/opt/gaussian# 
 
where R-3dstructure1ginp012.com keep ?how should I solve this problem?thank you a lot for your time.

**Comment by KristapsE** [comment]
You should cd into the directory you selected as the output directory - the *.com files should be there. Then you should run the command you just did, and it should work - or point to a problem.

**Comment by WeiYongqiang55** [comment]
i  find it saved in DP/nmr/ dir ,and now it works,thank you

**Comment by WeiYongqiang55** [comment]
change Gaussion.py line 289    solved my problem
GausPrefix = gausdir + "/g16<" +"/XXX/DP4-AI-master/nmr/"

**Comment by KristapsE** [comment]
Glad it solved the problem, but it doesn't seem like a very general solution. If you are running the latest DP4-AI version, then you should be able to select an output folder. 

I would suggest changing it back. Also I would suggest having the source code folder, and leave it unchanged and not use it for calculation or NMR data. Then - make a separate folder for each different molecule analysis, and put both the candidate sdf files and the corresponding NMR data in that folder. In the GUI then select the sdf files from this molecule folder, select NMR data from the molecule folder, and select the molecule folder as the output folder as well. This will ensure that the files generated for each analysis are located in well defined place, do not mix with each other, and do not lead to unexpected behaviour.
