### ISSUE TITLE
AttributeError: 'PyDP4WorkerObject' object has no attribute 'log_file'

### ISSUE THREAD

**Issue by WeiYongqiang55** [KristapsE/DP4-AI#24]
when I run  python PyDP4_GUI.py in DP4-AI-master source code dir,problem occur,
I put *.sdf and other data in other dir not in DP4-AI-master source code dir

(chem-env) root@ubuntu:/home/wyq/Downloads/Dp4-2/DP4-AI-master# python PyDP4_GUI.py 
/home/wyq/anaconda3/envs/chem-env/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/root/.pyxbld/temp.linux-x86_64-3.6/pyrex/ConfPrune.c: In function ‘__pyx_f_9ConfPrune_qtrjac’:
/root/.pyxbld/temp.linux-x86_64-3.6/pyrex/ConfPrune.c:7129:10: warning: variable ‘__pyx_v_ret’ set but not used [-Wunused-but-set-variable]
   double __pyx_v_ret[5][4];
          ^~~~~~~~~~~
Traceback (most recent call last):
  File "PyDP4_GUI.py", line 1026, in append_text
    self.worker.log_file.write(text)
AttributeError: 'PyDP4WorkerObject' object has no attribute 'log_file'
已放弃 (核心已转储)

**Comment by WeiYongqiang55** [comment]
I use ubuntu 16.04 & python 3.6.2

**Comment by WeiYongqiang55** [comment]
@KristapsE can you give some sugestion for me ?thank you

**Comment by KristapsE** [comment]
I'm afraid we haven't seen this issue before, so we will need to take a closer look as time allows. @HowarthA is the expert on the GUI things, so he may also take a look at some point.

**Comment by HowarthA** [comment]
Hi, The latest commit should solve this problem, let me know how it goes.

**Comment by WeiYongqiang55** [comment]
> Hi, The latest commit should solve this problem, let me know how it goes.

it works now ! thank you
