### ISSUE TITLE
AttributeError: module 'os' has no attribute 'copy'

### ISSUE THREAD

**Issue by WeiYongqiang55** [KristapsE/DP4-AI#25]
I am using latest code ,and I met this problem,

(chem-env) root@ubuntu:/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master# python PyDP4_GUI.py 
/home/wyq/anaconda3/envs/chem-env/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/root/.pyxbld/temp.linux-x86_64-3.6/pyrex/ConfPrune.c: In function ‘__pyx_f_9ConfPrune_qtrjac’:
/root/.pyxbld/temp.linux-x86_64-3.6/pyrex/ConfPrune.c:7129:10: warning: variable ‘__pyx_v_ret’ set but not used [-Wunused-but-set-variable]
   double __pyx_v_ret[5][4];
          ^~~~~~~~~~~
QLayout: Attempting to add QLayout "" to CalculationTab "", which already has a layout
QLayout: Attempting to add QLayout "" to CalculationTab "", which already has a layout
QLayout: Attempting to add QLayout "" to CalculationTab "", which already has a layout
QLayout: Attempting to add QLayout "" to CalculationTab "", which already has a layout
Traceback (most recent call last):
  File "PyDP4_GUI.py", line 665, in get_current_values
    os.copy(f, self.settings.OutputFolder)
AttributeError: module 'os' has no attribute 'copy'
已放弃 (核心已转储)
(chem-env) root@ubuntu:/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master#

**Comment by KristapsE** [comment]
Yes, that is definitely a typo, I have just pushed a fix for this to our development repo, just needs some testing.

**Comment by KristapsE** [comment]
A fix has been pushed, the line does not exist anymore, if new issues crop up, feel free to open a new issue.
