### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by WeiYongqiang55** [KristapsE/DP4-AI#26]
File "/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/MacroModel.py", line 134, in RunMacroModel
    if shutil.which(os.path.join(settings.SCHRODINGER,'bmin')) is None & settings.SCHRODINGER != "not-installed":
TypeError: unsupported operand type(s) for &: 'NoneType' and 'str'

in MacroModel.py line 134 ,& should be and
  if shutil.which(os.path.join(settings.SCHRODINGER,'bmin')) is None and settings.SCHRODINGER != "not-installed":

**Comment by KristapsE** [comment]
Yea, this was only meant as a quick fix, a more robust code has been put in it's place in the latest version I just pushed to this repo. This issue should now have been fixed - certainly didn't crop up in my testing, so I will close the issue, but feel free to reopen if it persists.
