### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './spectrum/struct/S-3dstructure1ginp001.com'

### ISSUE THREAD

**Issue by WeiYongqiang55** [KristapsE/DP4-AI#29]
I use terminal run Dp4 and I met this problem ,I searched all my ubuntu and I did not find any 
S-3dstructure1ginp001.com file !

(chem-env) root@ubuntu:/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master# python PyDP4.py  -w gnomes  ./spectrum/struct/S-3dstructure.sdf  ./spectrum/shouxingputu/ 
/home/wyq/anaconda3/envs/chem-env/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Settings read from settings.cfg:
  SCHRODINGER: /app/schrodinger2018-1
  TinkerPath: /home/ke291/TINKER/
  NWChemPath: nwchem
  GausPath: /root/opt/gaussian/g16
['./spectrum/struct/S-3dstructure.sdf']
./spectrum/shouxingputu/
NMR_path
Current working directory: /home/wyq/Downloads/DP4-AI-master3/DP4-AI-master
Initial input files: ['./spectrum/struct/S-3dstructure.sdf']
NMR file: [PosixPath('spectrum/shouxingputu/Carbon'), PosixPath('spectrum/shouxingputu/Proton')]
Workflow: gnomes

Generating diastereomers...
Getting inchi from file  ./spectrum/struct/S-3dstructure.sdf
Getting inchi from file  ./spectrum/struct/S-3dstructure.sdf
Number of diastereomers to be generated: 1
Isomer 0 inchi = InChI=1S/C16H20O/c1-16(11-13-7-3-2-4-8-13)12-17-15-10-6-5-9-14(15)16/h5-7,9-10H,2-4,8,11-12H2,1H3/t16-/m1/s1/f/
Generated input files: ['./spectrum/struct/S-3dstructure1']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using MacroModel

Setting up MacroModel files...
Macromodel input for ./spectrum/struct/S-3dstructure1 prepared.
MacroModel inputs: ['./spectrum/struct/S-3dstructure1.mae']
Running MacroModel...
/app/schrodinger2018-1/bmin ./spectrum/struct/S-3dstructure1
Macromodel job 1 of 1 completed.

Reading conformers...
./spectrum/struct/S-3dstructure1.log is matching conformational search output for ./spectrum/struct/S-3dstructure1
Energy window: 10.0 kJ/mol
./spectrum/struct/S-3dstructure1: 22 conformers read within energy window

Pruning conformers...
./spectrum/struct/S-3dstructure1: 22 conformers after pruning with 0A RMSD cutoff

Setting up geometry optimization calculations...
Traceback (most recent call last):
  File "PyDP4.py", line 718, in <module>
    main(settings)
  File "PyDP4.py", line 253, in main
    Isomers = DFT.SetupOptCalcs(Isomers, settings)
  File "/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/Gaussian.py", line 126, in SetupOptCalcs
    WriteGausFile(filename, iso.Conformers[num], iso.Atoms, charge, settings, 'opt')
  File "/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/Gaussian.py", line 326, in WriteGausFile
    f = open(Gausinp + '.com', 'w')
FileNotFoundError: [Errno 2] No such file or directory: './spectrum/struct/S-3dstructure1ginp001.com'
(chem-env) root@ubuntu:/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master#

**Comment by WeiYongqiang55** [comment]
still path problem ,I solved it

**Comment by KristapsE** [comment]
Sounded like it, glad to hear.
