### ISSUE TITLE
subprocess.CalledProcessError: Command '/root/opt/gaussian/g16/g16 < ./spectrum/struct/S-3dstructure1ginp001.com > ./spectrum/struct/S-3dstructure1ginp001.out' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by WeiYongqiang55** [KristapsE/DP4-AI#30]
(chem-env) root@ubuntu:/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master# python PyDP4.py  -w gnomes  ./spectrum/struct/S-3dstructure.sdf  /home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/spectrum/shouxingputu
/home/wyq/anaconda3/envs/chem-env/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Settings read from settings.cfg:
  SCHRODINGER: /app/schrodinger2018-1
  TinkerPath: /home/ke291/TINKER/
  NWChemPath: nwchem
  GausPath: /root/opt/gaussian/g16/g16
['./spectrum/struct/S-3dstructure.sdf']
/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/spectrum/shouxingputu
NMR_path
Current working directory: /home/wyq/Downloads/DP4-AI-master3/DP4-AI-master
Initial input files: ['./spectrum/struct/S-3dstructure.sdf']
NMR file: [PosixPath('/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/spectrum/shouxingputu/Carbon'), PosixPath('/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/spectrum/shouxingputu/Proton')]
Workflow: gnomes

Generating diastereomers...
Getting inchi from file  ./spectrum/struct/S-3dstructure.sdf
Getting inchi from file  ./spectrum/struct/S-3dstructure.sdf
Number of diastereomers to be generated: 1
Isomer 0 inchi = InChI=1S/C16H20O/c1-16(11-13-7-3-2-4-8-13)12-17-15-10-6-5-9-14(15)16/h5-7,9-10H,2-4,8,11-12H2,1H3/t16-/m1/s1/f/
Generated input files: ['./spectrum/struct/S-3dstructure1']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using MacroModel

Setting up MacroModel files...
Macromodel input for ./spectrum/struct/S-3dstructure1 prepared.
MacroModel inputs: ['./spectrum/struct/S-3dstructure1.mae']
Running MacroModel...
Valid ./spectrum/struct/S-3dstructure1.log exists, skipping...

Reading conformers...
./spectrum/struct/S-3dstructure1.log is matching conformational search output for ./spectrum/struct/S-3dstructure1
Energy window: 10.0 kJ/mol
./spectrum/struct/S-3dstructure1: 22 conformers read within energy window

Pruning conformers...
./spectrum/struct/S-3dstructure1: 22 conformers after pruning with 0A RMSD cutoff

Setting up geometry optimization calculations...
jobdir /home/wyq/Downloads/DP4-AI-master3/DP4-AI-master

Running geometry optimization calculations...

Running Gaussian DFT geometry optimizations locally...
/root/opt/gaussian/g16/g16 < ./spectrum/struct/S-3dstructure1ginp001.com > ./spectrum/struct/S-3dstructure1ginp001.out
/bin/sh: 1: cannot open ./spectrum/struct/S-3dstructure1ginp001.com: No such file
Traceback (most recent call last):
  File "PyDP4.py", line 718, in <module>
    main(settings)
  File "PyDP4.py", line 255, in main
    Isomers = DFT.RunOptCalcs(Isomers, settings)
  File "/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/Gaussian.py", line 258, in RunOptCalcs
    Completed = RunCalcs(GausJobs, settings)
  File "/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master/Gaussian.py", line 313, in RunCalcs
    outp = subprocess.check_output(GausPrefix + " < "  + f + ' > ' + f[:-3] + 'out', shell=True)
  File "/home/wyq/anaconda3/envs/chem-env/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/wyq/anaconda3/envs/chem-env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/root/opt/gaussian/g16/g16 < ./spectrum/struct/S-3dstructure1ginp001.com > ./spectrum/struct/S-3dstructure1ginp001.out' returned non-zero exit status 2.
(chem-env) root@ubuntu:/home/wyq/Downloads/DP4-AI-master3/DP4-AI-master#

**Comment by KristapsE** [comment]
This is probably an issue with giving input files as relative paths. Could you please have another look at our published data folder structure? The script and the GUI are really built with this folder structure in mind, and the script is only guaranteed to work well with this structure. 

https://www.repository.cam.ac.uk/handle/1810/303161

So, when starting a new calculation, please make a new directory, copy your 3D sdf structures in there. The process generally expects to have either 1 structure with possible diastereomers, which are then generated automatically, or several explicit structures without diastereomer generation. The folder also should contain the NMR data - either description, or raw Bruker NMR data folder. So you should have a folder with just 1 or more sdf files and either and NMR text file or raw NMR data. Then the standard way of launching the command line DP4-AI, as explained in the included README file, is to cd into that folder and then launch the script as 

PyDP4.py -w gmns -s chloroform Candidate CandidateNMR
for structure with 2 or more chiral centres or
PyDP4.py -w gmns -s chloroform Candidate1 Candidate2 CandidateNMR
for other types of isomers, where Candidate corresponds to Candidate.sdf file in the same folder. No paths are then needed or expected anywhere, just file names for structures and a file name or subfolder name for NMR data.

I suspect the other issues that you have reported ultimately come from not following this convention as well.
