### ISSUE TITLE
Tinker

### ISSUE THREAD

**Issue by zjp** [KristapsE/DP4-AI#33]
I'm trying to generalize this line in PyDP4.py:

`94:    TinkerPath = '/home/ah809/Downloads/tinker/' # Define the root folder for Tinker software`

But I'm having trouble finding Tinker, or maybe a correct copy of it. The version that my package manager installs includes just the params folder; I see no /bin/scan 

Where did you get your copy of Tinker?

**Comment by KristapsE** [comment]
Hi Zach! I always download TINKER from it's website:
https://dasher.wustl.edu/tinker/
Force Field Parameter Sets and Tinker Executables for Linux are the required packages and should get TINKER running.

By the way, the latest DP4-AI version contains a settings.cfg file, that hopefully makes the setting editing easier, as does not require editing the source code. It also overrides any defaults in PyDP4.py, so if you prefer editing PyDP4.py, you would need to delete the corresponding lines from settings.cfg

**Comment by zjp** [comment]
Thanks!
