### ISSUE TITLE
Error during import 'openbabel._openbabel'

### ISSUE THREAD

**Issue by CRZYMN** [KristapsE/DP4-AI#4]
![2020-04-11_23-40-54](https://user-images.githubusercontent.com/63485755/79048207-f9977480-7c4d-11ea-8fe7-a48e0b86957b.jpg)
![2020-04-11_23-35-07](https://user-images.githubusercontent.com/63485755/79048123-68280280-7c4d-11ea-92dc-4cde95c53eaa.jpg)
Could you please kindly help to see why the errors pop-up? openbabel V 3.0 has been installed. Tried to usinstall and re-install openbabel while the error still existed.
Thanks a lot.

**Comment by HowarthA** [comment]
Hi, we are currently using Openbabel version 2.4.1. Openbabel version 3.0 isn't backward compatible, installing version 2.4.1 should fix your issue. 

Thanks,

Alex

**Comment by CRZYMN** [comment]
Mant thanks for your suggestions. I would check that.
