### ISSUE TITLE
NWChem.py line 242 typo - Populating NMROutputFiles instead of OptOutputFiles.

### ISSUE THREAD

**Issue by danny305** [KristapsE/DP4-AI#40]
In the RunOptCalc() function in NWChem.py I think there is a typo at line 242:

The for loop should populate isoOptOutputFiles instead of isoNMROutputFiles?

So change: 
``` python3
for iso in Isomers:
        iso.NMROutputFiles.extend([x[:-3] + '.nwo' for x in iso.OptInputFiles if (x[:-3] + '.nwo') in Completed])
```
To
``` python3
for iso in Isomers:
        iso.OptOutputFiles.extend([x[:-3] + '.nwo' for x in iso.OptInputFiles if (x[:-3] + '.nwo') in Completed])
```

After running the RunOptCalc() and trying to ReadGeometries(), I am getting the following error: 
NWChem.py, ReadGeometries: No geometry optimisation output files found, geometries could not be read. Quitting.

I believe this is because of the typo ^^.

**Comment by danny305** [comment]
Also, I believe that line 236 meant to print the OptInputFiles and not the NMRInputFiles. This is just an observation from comparing RunOptCalc() to RunECalcs() and RunNMRCalcs().

**Comment by zjp** [comment]
Can you try my unmerged patch in #38 and see if it works for you?

**Comment by danny305** [comment]
No I was trying to generate data. By making the changes I suggested above, NWChem optimization works.

**Comment by KristapsE** [comment]
Yup, that definitely looks like a typo on our part, I'll try to fix it tonight and merge it. Good catch!

**Comment by KristapsE** [comment]
So I have made the changes you suggested - they totally make sense to me, but could you please test the current version and let me know if it works as expected for you?

**Comment by danny305** [comment]
Works on my end. Thanks.
