### ISSUE TITLE
calculating 1H J-coupling constants

### ISSUE THREAD

**Issue by danny305** [KristapsE/DP4-AI#42]
This is more of a question than an issue. I am having a hard time figuring out how to tell nwchem to calculate not just the chemical shift for protons but also the coupling constants. How can I use the cli to also get the coupling constants?

Danny

**Comment by KristapsE** [comment]
We have not implemented any automated way of requesting the coupling constant calculation from NWChem or Gaussian. The main reason being that coupling calculations are much more expensive than shift calculations, but we haven't found significant improvement in structure elucidation from DFT coupling constants. I had a look at it couple years ago an basically found that using Karplus J-values on a conformer ensemble is a much better return on computer time investment, as Karplus J-values are effectively free. In principle calculating coupling constants should be an excellent tool for structure elucidation, but there are just to many complications that need to be solved first. The other complications being that it's much more difficult to get unambiguous benchmark data, hence no error statistical models, and that one needs even better conformational geometries and energies, which without explicit solvent is almost impossible to achieve.

Having said that, you could modify WriteNWChemFile and or NMRSuffix functions in NWChem.py to include SPINSPIN keyword in the NWChem input files - this would allow you to run coupling calculations on many files at once. For analysis and result output, further modifications would be needed.

http://www.nwchem-sw.org/index.php/Properties

Hope this helps.
