### ISSUE TITLE
DP4-AI on Computational Clusters

### ISSUE THREAD

**Issue by zjp** [KristapsE/DP4-AI#43]
In the code of PyDP4.py there is a section on computational clusters that says "This should probably be moved to relevant *.py files as[ it's ] Cambridge specific"

What was your original concept for what these *.py files would do? I'm working on a script to generate job files for XSEDE supercomputers in the United States, but it's easier to write an expert system with more than one example in mind.

**Comment by KristapsE** [comment]
All the code is there in GaussianDarwin.py and GaussianZiggy.py. They are invoked by selecting a different DFT switch, which are defined in DFTpackages in PyDP4.py, line 50. They reuse as much of Gaussian.py as possible, but has code to interface with our local section cluster in the department, as well as the Cambridge supercomputer. If XSEDE uses SLURM scheduling and allows passwordless (public/private key) ssh access, then the basic process will be the same for you as well. I'd suggest you have a look and see what you can use to make NWChemXSEDE.py or similar. Hope this helps.
