### ISSUE TITLE
Tinker

### ISSUE THREAD

**Issue by whe280** [KristapsE/DP4-AI#48]
@KristapsE 
hello，I am very interested in your research. There was an error while running this software. I have installed Tinker and G16, and I sincerely hope to get your help and advice. My command line is ‘python3 PyDP4.py -s chloroform -w gmns -m t -f mmff KE.sdf NMR_folder’.

==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Settings read from settings.cfg:
  SCHRODINGER: 
  TinkerPath: /home/node0/work/whe/tinker
  NWChemPath: nwchem
  GausPath: g16
['KE.sdf']
NMR_folder
NMR_path
/home/node0/work/whe/DP4-AI-master/NMR_folder
Current working directory: /home/node0/work/whe/DP4-AI-master
Initial input files: ['KE.sdf']
NMR file: [PosixPath('/home/node0/work/whe/DP4-AI-master/NMR_folder/Carbon'), PosixPath('/home/node0/work/whe/DP4-AI-master/NMR_folder/Proton')]
Workflow: gmns

Generating diastereomers...
Getting inchi from file  KE.sdf
Getting inchi from file  KE.sdf
Number of diastereomers to be generated: 2
Isomer 0 inchi = InChI=1S/C6H10O/c1-5-3-2-4-6(5)7/h2-3,5-7H,4H2,1H3/t5-,6-/m0/s1/f/
Isomer 1 inchi = InChI=1S/C6H10O/c1-5-3-2-4-6(5)7/h2-3,5-7H,4H2,1H3/t5-,6+/m0/s1/f/
Generated input files: ['KE1', 'KE2']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using Tinker

Setting up Tinker files...
Tinker input for KE1 prepared.
Tinker input for KE2 prepared.

Running Tinker...
/home/node0/work/whe/tinker/bin/scan KE1 0 10 20 0.00001 | tee ./KE1.tout
mmff.prm

Tinker job 1 of 2 completed.
/home/node0/work/whe/tinker/bin/scan KE2 0 10 20 0.00001 | tee ./KE2.tout
mmff.prm

Tinker job 2 of 2 completed.
KE1 is matching conformational search output for KE1
Reading KE1
Tinker output KE1 is corrupted, aborting.

**Comment by KristapsE** [comment]
Hi, what do the *.tout files look like? To me it looks like TINKER launches, but doesn't finish correctly. Have you tried running TINKER manually outside the script? Did you download the mmff.prm file from the TINKER website?

**Comment by whe280** [comment]
Hi,Thank you for your prompt reply.I haven't tried running TINKER manually outside the script.I downloaded Tinker8 at https://github.com/TinkerTools/tinker and compiled 
source code. mmff.prm file is also from the above website.The content of *.tout file is as follows.




     ######################################################################
   ##########################################################################
  ###                                                                      ###
 ###            Tinker  ---  Software Tools for Molecular Design            ###
 ##                                                                          ##
 ##                       Version 8.8.3  November 2020                       ##
 ##                                                                          ##
 ##               Copyright (c)  Jay William Ponder  1990-2020               ##
 ###                           All Rights Reserved                          ###
  ###                                                                      ###
   ##########################################################################
     ######################################################################




 Enter Potential Parameter File Name :  
 Additional Partial Charges for Specific Atoms :


        Atom                Charge


           1               -0.2882
           2                0.1382
           3                0.2800
           4                0.1382
           5               -0.2882
           6                0.0000
           7                0.0000
           8                0.0000
           9                0.0000
          10                0.1500
          11                0.1500
          12                0.0000
          13                0.0000
          14                0.0000
          15                0.0000
          16               -0.6800
          17                0.4000


 Number of Torsions Used in Derivative Computation :     2


 Enter RMS Gradient per Atom Criterion [0.0001] :  
 Generating Seed Point for Potential Energy Surface Scan




    Potential Surface Map       Minimum      1           100000.0000




 Normal Mode Local Search       Minimum      1


    Search Direction   1                                      >>>>>>
    Search Direction   2                                      >>>>>>
    Search Direction   3                                      >>>>>>
    Search Direction   4                                      >>>>>>


For the *.tout files , please see attached release notes.Really appreciate your help! Look forward to your reply.


On 1/4/2021 23:12，KristapsE<notifications@github.com> wrote：

Hi, what do the *.tout files look like? To me it looks like TINKER launches, but doesn't finish correctly. Have you tried running TINKER manually outside the script? Did you download the mmff.prm file from the TINKER website?

**Comment by KristapsE** [comment]
This seems to be closely connected, perhaps identical issue to #36. A patch to be copied over the RunTinker function in Tinker.py has been suggested by @gkxiao . I haven't had time to properly test it on my end, so I haven't yet incorporated in the main branch, but feel free to try and see if it resolves the issue.

**Comment by whe280** [comment]
Really appreciate your reply!With reference of the opinion from @gkxiao ,I modified the RunTinker function in Tinker.py.The content of *.tout file is as follows.


     ######################################################################
   ##########################################################################
  ###                                                                      ###
 ###            Tinker  ---  Software Tools for Molecular Design            ###
 ##                                                                          ##
 ##                       Version 8.8.3  November 2020                       ##
 ##                                                                          ##
 ##               Copyright (c)  Jay William Ponder  1990-2020               ##
 ###                           All Rights Reserved                          ###
  ###                                                                      ###
   ##########################################################################
     ######################################################################




 Additional Partial Charges for Specific Atoms :


        Atom                Charge


           1               -0.2882
           2                0.1382
           3                0.2800
           4                0.1382
           5               -0.2882
           6                0.0000
           7                0.0000
           8                0.0000
           9                0.0000
          10                0.1500
          11                0.1500
          12                0.0000
          13                0.0000
          14                0.0000
          15                0.0000
          16               -0.6800
          17                0.4000


 Number of Torsions Used in Derivative Computation :     2


 Generating Seed Point for Potential Energy Surface Scan




    Potential Surface Map       Minimum      1           100000.0000




 Normal Mode Local Search       Minimum      1


    Search Direction   1                                      >>>>>>
    Search Direction   2                                      >>>>>>
    Search Direction   3                                      >>>>>>
    Search Direction   4                                      >>>>>>










On 1/5/2021 20:20，KristapsE<notifications@github.com> wrote：

This seems to be closely connected, perhaps identical issue to #36. A patch to be copied over the RunTinker function in Tinker.py has been suggested by @gkxiao . I haven't had time to properly test it on my end, so I haven't yet incorporated in the main branch, but feel free to try and see if it resolves the issue.

**Comment by whe280** [comment]
Thanks a lot! According to your suggestion,I tried with AT3 .
The command I used was:
python3 PyDP4.py -s chloroform -w gmns -m t -f mmff AT3_.sdf NMR_folder






==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0


Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================




Settings read from settings.cfg:
  SCHRODINGER: 
  TinkerPath: /home/node0/work/whe/tinker
  NWChemPath: nwchem
  GausPath: g16
['AT3_.sdf']
NMR_folder
NMR_path
/home/node0/work/whe/DP4-AI-master/NMR_folder
Current working directory: /home/node0/work/whe/DP4-AI-master
Initial input files: ['AT3_.sdf']
NMR file: [PosixPath('/home/node0/work/whe/DP4-AI-master/NMR_folder/Carbon'), PosixPath('/home/node0/work/whe/DP4-AI-master/NMR_folder/Proton')]
Workflow: gmns


Generating diastereomers...
Getting inchi from file  AT3_.sdf
Getting inchi from file  AT3_.sdf
Number of diastereomers to be generated: 2
Isomer 0 inchi = InChI=1S/C13H19F2NO/c1-3-13(9(2)8-17)16-7-10-11(14)5-4-6-12(10)15/h4-6,9,13,16-17H,3,7-8H2,1-2H3/t9-,13+/m0/s1/f/
Isomer 1 inchi = InChI=1S/C13H19F2NO/c1-3-13(9(2)8-17)16-7-10-11(14)5-4-6-12(10)15/h4-6,9,13,16-17H,3,7-8H2,1-2H3/t9-,13-/m0/s1/f/
Generated input files: ['AT3_1', 'AT3_2']


Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using Tinker


Setting up Tinker files...
Tinker input for AT3_1 prepared.
Tinker input for AT3_2 prepared.


Running Tinker...
/home/node0/work/whe/tinker/bin/scan AT3_1 /home/node0/work/whe/tinker/params/mmff.prm 0 10 20 0.00001 | tee ./AT3_1.tout
Tinker job 1 of 2 completed.
/home/node0/work/whe/tinker/bin/scan AT3_2 /home/node0/work/whe/tinker/params/mmff.prm 0 10 20 0.00001 | tee ./AT3_2.tout
Tinker job 2 of 2 completed.
AT3_1 is matching conformational search output for AT3_1
Reading AT3_1
Traceback (most recent call last):
  File "PyDP4.py", line 718, in <module>
    main(settings)
  File "PyDP4.py", line 211, in main
    Isomers = Tinker.ReadConformers(TinkerOutputs, Isomers, settings)
  File "/home/node0/work/whe/DP4-AI-master/Tinker.py", line 118, in ReadConformers
    atoms, conformers, charge, AbsEs = ReadTinker(outp, settings, atypes, anums)
  File "/home/node0/work/whe/DP4-AI-master/Tinker.py", line 155, in ReadTinker
    MinE = min(energies)
ValueError: min() arg is an empty sequence




The content of *.tout file is as follows.


     ######################################################################
   ##########################################################################
  ###                                                                      ###
 ###            Tinker  ---  Software Tools for Molecular Design            ###
 ##                                                                          ##
 ##                       Version 8.8.3  November 2020                       ##
 ##                                                                          ##
 ##               Copyright (c)  Jay William Ponder  1990-2020               ##
 ###                           All Rights Reserved                          ###
  ###                                                                      ###
   ##########################################################################
     ######################################################################




 Additional Partial Charges for Specific Atoms :


        Atom                Charge


           1                0.0000
           2                0.0000
           3                0.2700
           4                0.0000
           5                0.2800
           6               -0.6800
           7               -0.9000
           8                0.4135
           9               -0.1500
          10               -0.1500
          11                0.1900
          12               -0.1435
          13                0.1900
          14               -0.1500
          15                0.1500
          16                0.1500
          17                0.1500
          18               -0.1900
          19               -0.1900
          20                0.0000
          21                0.0000
          22                0.0000
          23                0.0000
          24                0.0000
          25                0.0000
          26                0.0000
          27                0.0000
          28                0.4000
          29                0.0000
          30                0.0000
          31                0.0000
          32                0.0000
          33                0.0000
          34                0.0000
          35                0.0000
          36                0.3600


 INITROT  --  Rotation about     8     7 occurs more than once in Z-matrix


 Tinker is Unable to Continue; Terminating the Current Calculation




On 1/5/2021 21:35，KristapsE<notifications@github.com> wrote：

In that case it might be connected with the particular molecule, which is very rigid and it might be that TINKER is unable to find any conformers at all. Perhaps try with one of the slightly more flexible ones from the test set, like AT3?

**Comment by KristapsE** [comment]
This seems like a bug in TINKER. According to this link, the atoms need to be renumbered in the input file:|
INITROT -- Rotation about 8 7 occurs more than once in Z-matrix

DP4-AI includes a utility TreeRenum.py, which I wrote 5 years ago when encountering similar problems with TINKER. I have not used it in a while, but you might try renumbering AT3.sdf with that and then try again. It usually resolved TINKER issues back then.

**Comment by whe280** [comment]
Hello, Thank you for your suggestion, and I am very sorry that I did not reply to your message in time due to going out for the exam.
this is the result of running the code.May I ask if I did something incorrectly


The following is the content of AT3_r.sdf ,which was renumbered by AT3_.sdf using the TreeRenumSDF function inTreeRenum.py.


 OpenBabel01072109163D


 36 35  0  0  1  0  0  0  0  0999 V2000
   -4.6167    4.0212    0.7531 F   0  0  0  0  0  0  0  0  0  0  0  0
   -5.4903    3.4592    1.6250 C   0  0  0  0  0  0  0  0  0  0  0  0
   -6.8629    3.4439    1.3097 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.7891    2.8701    2.2023 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.3403    2.3203    3.4187 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.9691    2.3417    3.7405 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.0339    2.9026    2.8409 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5573    2.9309    3.1981 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9374    1.6079    3.2162 N   0  0  0  0  0  2  0  0  0  0  0  0
   -2.1774    1.2670    2.0151 C   0  0  2  0  0  0  0  0  0  0  0  0
   -0.6663    1.2396    2.4012 C   0  0  2  0  0  0  0  0  0  0  0  0
   -0.1103    2.6678    2.5988 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1870    2.6359    3.1638 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7703    2.1786    2.5761 H   0  0  0  0  0  0  0  0  0  0  0  0
   -7.2060    3.8755    0.3788 H   0  0  0  0  0  0  0  0  0  0  0  0
   -8.8409    2.8518    1.9600 H   0  0  0  0  0  0  0  0  0  0  0  0
   -8.0407    1.8831    4.1146 H   0  0  0  0  0  0  0  0  0  0  0  0
   -5.5595    1.8316    4.9266 F   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0147    3.6196    2.5471 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4830    3.3499    4.2028 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1665    1.2922    3.2161 H   0  0  0  0  0 15  0  0  0  0  0  0
   -2.7297   -0.0882    1.5191 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.1995   -0.0326    1.0785 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5128   -0.9846    0.6511 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3451    2.0020    1.2261 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5707    0.7016    3.3465 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.2079    0.4809    1.3820 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2633    0.5206    1.6491 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7415    3.2394    3.2794 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0911    3.2098    1.6517 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1603   -0.4295    0.6550 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6071   -0.8526    2.2879 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.8540    0.1774    1.9238 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3578    0.7420    0.3280 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0465   -0.5779    1.3445 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1009    0.8923    0.3785 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  7  1  0  0  0  0
  3  2  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  5 17  1  0  0  0  0
  6 18  1  0  0  0  0
  7  8  1  0  0  0  0
  7  6  2  0  0  0  0
  8  9  1  0  0  0  0
  8 20  1  0  0  0  0
 10 25  1  6  0  0  0
 10 11  1  0  0  0  0
 10  9  1  0  0  0  0
 11 12  1  0  0  0  0
 11 26  1  1  0  0  0
 12 13  1  0  0  0  0
 12 29  1  0  0  0  0
 14 13  1  0  0  0  0
 15  3  1  0  0  0  0
 16  4  1  0  0  0  0
 19  8  1  0  0  0  0
 22 10  1  0  0  0  0
 22 32  1  0  0  0  0
 23 22  1  0  0  0  0
 23 33  1  0  0  0  0
 24 23  1  0  0  0  0
 27 28  1  0  0  0  0
 27 11  1  0  0  0  0
 30 12  1  0  0  0  0
 31 22  1  0  0  0  0
 34 23  1  0  0  0  0
 35 27  1  0  0  0  0
 36 27  1  0  0  0  0
M  END
$$$$


On 1/5/2021 22:14，KristapsE<notifications@github.com> wrote：

This seems like a bug in TINKER. According to this link, the atoms need to be renumbered in the input file:|
INITROT -- Rotation about 8 7 occurs more than once in Z-matrix

DP4-AI includes a utility TreeRenum.py, which I wrote 5 years ago when encountering similar problems with TINKER. I have not used it in a while, but you might try renumbering AT3.sdf with that and then try again. It usually resolved TINKER issues back then.

**Comment by KristapsE** [comment]
So the TreeRenum.py will not run the DP4-AI process itself. Its only purpose is to prepare an sdf file that TINKER likes better. I would suggest you renumber the input file with this (as you have already done), and then try the DP4-AI script again with the renumbered sdf, instead of the original.

**Comment by whe280** [comment]
I tried the DP4-AI script again with the renumbered sdf.The renumbered sdf seems to have some problems running in InchiGen.py. I tried my best to check it for  a while, but due to poor programming ability, I didn’t find the reason.
The command I used was:
`python3 PyDP4.py -s chloroform -w gmns -m t -f mmff AT3_r.sdf NMR_folder`
The result was:
`Generating diastereomers...
Getting inchi from file  AT3_r.sdf
[19:39:29] WARNING: Accepted unusual valence(s): N(2)
Getting inchi from file  AT3_r.sdf
[19:39:29] WARNING: Accepted unusual valence(s): N(2)
Number of diastereomers to be generated: 4
Traceback (most recent call last):
  File "PyDP4.py", line 718, in <module>
    main(settings)
  File "PyDP4.py", line 188, in main
    settings.InputFiles = InchiGen.GenDiastereomers(settings.InputFiles[0], settings.SelectedStereocentres)
  File "/home/node0/work/whe/DP4-AI-master/InchiGen.py", line 306, in GenDiastereomers
    ds_inchis = [FixTautProtons(f, i, aux) for i in ds_inchis]
  File "/home/node0/work/whe/DP4-AI-master/InchiGen.py", line 306, in <listcomp>
    ds_inchis = [FixTautProtons(f, i, aux) for i in ds_inchis]
  File "/home/node0/work/whe/DP4-AI-master/InchiGen.py", line 53, in FixTautProtons
    amap = GetInchiRenumMap(AuxInfo)
  File "/home/node0/work/whe/DP4-AI-master/InchiGen.py", line 45, in GetInchiRenumMap
    amap = [int(x) for x in RenumLayer[2:].split(',')]
  File "/home/node0/work/whe/DP4-AI-master/InchiGen.py", line 45, in <listcomp>
    amap = [int(x) for x in RenumLayer[2:].split(',')]
ValueError: invalid literal for int() with base 10: '13;21'`

**Comment by KristapsE** [comment]
Have you tried looking at the starting sdf and the resulting sdf with Avogadro or jmol or similar? The differences, if any, might provide clues as to what is going wrong.

You could also try skipping the diastereomer generation for now. Just renumber the AT3_1.sdf, AT3_2.sdf etc, and then submit them to PyDP4.py using
python3 PyDP4.py -s chloroform -w mns -m t -f mmff AT3_1r.sdf AT3_2r.sdf NMR_folder

**Comment by gkxiao** [comment]
If you reprepare the AT3_.sdf, it works.
Here is the AT3_.sdf file I used:
AT3
  Mrv2008 01072123113D          

 36 36  0  0  0  0            999 V2000
   -0.0166   -0.9858   -2.5510 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2070   -1.2272   -3.9255 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3256   -0.1533   -4.8203 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2619    1.1646   -4.3424 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0767    1.4134   -2.9680 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0597    0.3414   -2.0470 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0803   -2.0288   -1.7688 F   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0350    2.6600   -2.5763 F   0  0  0  0  0  0  0  0  0  0  0  0
    0.2819    0.6063   -0.5949 C   0  0  1  0  0  0  0  0  0  0  0  0
   -1.0100    0.9025    0.0782 N   0  0  2  0  0  0  0  0  0  0  0  0
   -1.0442    1.0602    1.5661 C   0  0  2  0  0  0  0  0  0  0  0  0
   -0.2827    2.3591    2.0006 C   0  0  1  0  0  0  0  0  0  0  0  0
   -0.6427   -0.2454    2.3653 C   0  0  1  0  0  0  0  0  0  0  0  0
   -0.7662    3.6633    1.3226 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5989   -0.0430    3.9106 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5755   -1.4625    2.0705 C   0  0  2  0  0  0  0  0  0  0  0  0
   -1.5673   -1.8463    0.7024 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2618   -2.1855   -4.2795 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4605   -0.3306   -5.8173 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3540    1.9428   -4.9997 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.7690   -0.2534   -0.1389 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.9655    1.4469   -0.4687 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6658    0.1614   -0.1691 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0965    1.2444    1.7996 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4216    2.5266    3.0694 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.7884    2.2426    1.8210 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.3667   -0.5349    2.0708 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6194    3.6210    0.2433 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8242    3.8313    1.5356 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1988    4.5130    1.7142 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.2034    0.6376    4.1924 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5498    0.3566    4.2681 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4001   -0.9842    4.4277 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6016   -1.2276    2.3606 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2567   -2.3405    2.6409 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2487   -2.5476    0.6314 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  1  6  2  0  0  0  0
  1  7  1  0  0  0  0
  5  8  1  0  0  0  0
  6  9  1  0  0  0  0
  9 10  1  0  0  0  0
 11 10  1  0  0  0  0
 11 12  1  0  0  0  0
 11 13  1  0  0  0  0
 12 14  1  0  0  0  0
 13 15  1  0  0  0  0
 13 16  1  0  0  0  0
 16 17  1  0  0  0  0
  2 18  1  0  0  0  0
  3 19  1  0  0  0  0
  4 20  1  0  0  0  0
  9 21  1  0  0  0  0
  9 22  1  0  0  0  0
 10 23  1  0  0  0  0
 11 24  1  0  0  0  0
 12 25  1  0  0  0  0
 12 26  1  0  0  0  0
 13 27  1  0  0  0  0
 14 28  1  0  0  0  0
 14 29  1  0  0  0  0
 14 30  1  0  0  0  0
 15 31  1  0  0  0  0
 15 32  1  0  0  0  0
 15 33  1  0  0  0  0
 16 34  1  0  0  0  0
 16 35  1  0  0  0  0
 17 36  1  0  0  0  0
M  END
$$$$
`
`

**Comment by whe280** [comment]
Hello, thank you for your reply, I used the AT3_.sdf and command line you provided.It seems that Tinker failed when it first started running, and we are trying to find the error related to Tinker.
The result is：
```
Running Tinker...
/home/node0/work/whe/tinker//bin/scan AT3_1 0 10 20 0.00001 | tee ./AT3_1.tout
Tinker job 1 of 2 completed.
/home/node0/work/whe/tinker//bin/scan AT3_2 0 10 20 0.00001 | tee ./AT3_2.tout
Tinker job 2 of 2 completed.
AT3_1 is matching conformational search output for AT3_1
Reading AT3_1
Traceback (most recent call last):
  File "PyDP4.py", line 719, in <module>
    main(settings)
  File "PyDP4.py", line 212, in main
    Isomers = Tinker.ReadConformers(TinkerOutputs, Isomers, settings)
  File "/home/node0/work/whe/DP4-AI-master/Tinker.py", line 118, in ReadConformers
    atoms, conformers, charge, AbsEs = ReadTinker(outp, settings, atypes, anums)
  File "/home/node0/work/whe/DP4-AI-master/Tinker.py", line 155, in ReadTinker
    MinE = min(energies)
ValueError: min() arg is an empty sequence

```
And here is the last 50 lines of AT3_1.sdf：
```
(my-rdkit-env) [node0@zhang8 DP4-AI-master]$ tail -50 AT3_1.tout

 Additional Partial Charges for Specific Atoms :

        Atom                Charge

           1                0.1900
           2               -0.1500
           3               -0.1500
           4               -0.1500
           5                0.1900
           6               -0.1435
           7               -0.1900
           8               -0.1900
           9                0.4135
          10               -0.9000
          11                0.2700
          12                0.0000
          13                0.0000
          14                0.0000
          15                0.0000
          16                0.2800
          17               -0.6800
          18                0.1500
          19                0.1500
          20                0.1500
          21                0.0000
          22                0.0000
          23                0.3600
          24                0.0000
          25                0.0000
          26                0.0000
          27                0.0000
          28                0.0000
          29                0.0000
          30                0.0000
          31                0.0000
          32                0.0000
          33                0.0000
          34                0.0000
          35                0.0000
          36                0.4000

 Number of Torsions Used in Derivative Computation :     9

 Generating Seed Point for Potential Energy Surface Scan


 GRADIENT  --  Illegal Value for the Total Potential Energy

 Tinker is Unable to Continue; Terminating the Current Calculation
```

**Comment by whe280** [comment]
Thanks a lot!I have tried  looking at the starting sdf and the resulting sdf with Avogadro and not found the differences.
The command I used was:
python3 PyDP4.py -s chloroform -w mns -m t -f mmff AT3_1r.sdf AT3_2r.sdf NMR_folder
It seems that Tinker failed when it first started running, and we are trying to find the error related to Tinker.


Here is the last 50 lines of AT3_1r.tout：
(my-rdkit-env) [node0@zhang8 DP4-AI-master]$ tail -50 AT3_1r.tout


 Additional Partial Charges for Specific Atoms :


        Atom                Charge


           1               -0.1900
           2                0.1900
           3               -0.1500
           4               -0.1500
           5               -0.1500
           6                0.1900
           7               -0.1435
           8                0.4135
           9               -0.9000
          10                0.2700
          11                0.0000
          12                0.2800
          13               -0.6800
          14                0.4000
          15                0.1500
          16                0.1500
          17                0.1500
          18               -0.1900
          19                0.0000
          20                0.0000
          21                0.3600
          22                0.0000
          23                0.0000
          24                0.0000
          25                0.0000
          26                0.0000
          27                0.0000
          28                0.0000
          29                0.0000
          30                0.0000
          31                0.0000
          32                0.0000
          33                0.0000
          34                0.0000
          35                0.0000
          36                0.0000


 Number of Torsions Used in Derivative Computation :     9


 Generating Seed Point for Potential Energy Surface Scan




 GRADIENT  --  Illegal Value for the Total Potential Energy


 Tinker is Unable to Continue; Terminating the Current Calculation




On 1/7/2021 22:08，KristapsE<notifications@github.com> wrote：

Have you tried looking at the starting sdf and the resulting sdf with Avogadro or jmol or similar? The differences, if any, might provide clues as to what is going wrong.

You could also try skipping the diastereomer generation for now. Just renumber the AT3_1.sdf, AT3_2.sdf etc, and then submit them to PyDP4.py using
python3 PyDP4.py -s chloroform -w mns -m t -f mmff AT3_1r.sdf AT3_2r.sdf NMR_folder

**Comment by KristapsE** [comment]
Frankly, I am out of ideas, and ultimately I'm afraid it is an issue with TINKER, and not with DP4-AI. TINKER is not producing any conformers, so DP4-AI cannot generate any Gaussian input files. I can only suggest that you try contacting TINKER developers, but from my experience they are not too responsive. One last idea - could you perhaps try the precompiled binaries, instead of your compiled-from-source version, as others seem to have more luck with running the TINKER workflow?

**Comment by whe280** [comment]
Thank you for your patience to provide me with so many valuable suggestions these days. I will actively adopt your suggestions to update glibc to try to use the precompiled binaries, and try to find the problem with Tinker.Thanks and respect to you again.
On 1/8/2021 23:20，KristapsE<notifications@github.com> wrote：

Frankly, I am out of ideas, and ultimately I'm afraid it is an issue with TINKER, and not with DP4-AI. TINKER is not producing any conformers, so DP4-AI cannot generate any Gaussian input files. I can only suggest that you try contacting TINKER developers, but from my experience they are not too responsive. One last idea - could you perhaps try the precompiled binaries, instead of your compiled-from-source version, as others seem to have more luck with running the TINKER workflow?

**Comment by whe280** [comment]
Hi,I have good news to share with you that the problem has been solved. PyDP4 process completed successfully after  trying the precompiled binaries.Thanks a lot！
I ran Tinker Testing Outside the Script  and found that Tinker failed to run (although the compilation process was fine,and it doesn't matter).


On 1/8/2021 23:20，KristapsE<notifications@github.com> wrote：

Frankly, I am out of ideas, and ultimately I'm afraid it is an issue with TINKER, and not with DP4-AI. TINKER is not producing any conformers, so DP4-AI cannot generate any Gaussian input files. I can only suggest that you try contacting TINKER developers, but from my experience they are not too responsive. One last idea - could you perhaps try the precompiled binaries, instead of your compiled-from-source version, as others seem to have more luck with running the TINKER workflow?

**Comment by KristapsE** [comment]
That's great to hear! I guess recommendation to use precompiled TINKER is something to add to the documentation.
