### ISSUE TITLE
Request for a standard file

### ISSUE THREAD

**Issue by sevenup233** [KristapsE/DP4-AI#6]
Hello,

I have opened PyDP4_GUI.py to see the GUI platform, but when i try to imput my data and choose options to run the program, it always crash after i push the 'Calculate' buttom. Im not a professional of computational chemistry, but i realy want to experience this magic function. Could you give a successful file for example please.

Thank a lot.
![00](https://user-images.githubusercontent.com/24826378/79070192-afbe9500-7d06-11ea-8a7f-efccf0e39755.png)

**Comment by KristapsE** [comment]
Hi sevenup! All of the computational files as well as NMR data, both manually interpreted and raw data have been released on the Cambridge repository here:
https://www.repository.cam.ac.uk/handle/1810/303161

All of the folders are organised for easy running of the program, as these are essentially the same folders we used during the development. I suggest you give some these a go and let us know if any further issues arise.
