### ISSUE TITLE
the Gaussian version

### ISSUE THREAD

**Issue by ccyx1997** [KristapsE/DP4-AI#7]
I have tried it for 3 days in my computer with win system. The Gaussion09 barried me from runing a test of AT2. I think there should be a .chk file to run it properly. There are somenting different between win and linux but I think It can be uesd on win.  What is the version of g09,Tinker and Schrodinger? I'm very intresting and exciting for your work.

**Comment by KristapsE** [comment]
Sorry to hear that you are experiencing problems. As mentioned in the README, the workflow has been written and extensively tested on Linux (Ubuntu 16.04-18.04) systems. In theory it should work on Windows, but unlikely to do so out of the box without minor modifications. Specifically file and folder paths are treated slightly differently by the two OSes. Also please bear in mind that minor modifications will usually be required to make sure that the workflow finds your molecular mechanics and DFT software. It would be helpful if you could provide the specific error messages that you experience when trying to run the workflow.

For test data, all of the data used in the development and testing of the workflow, including computational files as well as NMR data, both manually interpreted and raw data have been released on the Cambridge repository here:
https://www.repository.cam.ac.uk/handle/1810/303161

I suggest you try downloading some of these and running the workflow in one of the folders with appropriate arguments. It should not even require the molecular mechanics and DFT software with all the computational files already present.

We used Gaussian 09 for this work, but Gaussian 16 should work equally well by modifying line 288 in Gaussian.py. TINKER v8.7 was used and MacroModel versions are the ones bundled with Schrodinger Suite 2018 and 2019 releases.
