### ISSUE TITLE
OSError: Bad input file /home/l3ul/Downloads/dp4/AT1_.sdf

### ISSUE THREAD

**Issue by L3ul** [KristapsE/DP4-AI#8]
> Initial input files: ['AT1_.sdf']
NMR file: NMR_folder
Workflow: gmona
>Generating diastereomers...
Get inchi f AT1_.sdf
Traceback (most recent call last):
  File "PyDP4_GUI.py", line 2001, in runPyDP4
    self.NMRData, self.Isomers, self.settings, self.DP4Data = PyDP4.main(ui.table_widget.Tab1.settings)
  File "/home/l3ul/Downloads/dp4/PyDP4.py", line 189, in main
    settings.InputFiles = InchiGen.GenDiastereomers(settings.InputFiles[0], settings.SelectedStereocentres)
  File "/home/l3ul/Downloads/dp4/InchiGen.py", line 296, in GenDiastereomers
    inchi, aux = GetInchi(f)
  File "/home/l3ul/Downloads/dp4/InchiGen.py", line 167, in GetInchi
    m = Chem.MolFromMolFile(cwd + '/' + f ,removeHs = False)
OSError: Bad input file /home/l3ul/Downloads/dp4/AT1_.sdf

I'm on a Debian 10.3 VM (Windows 10 host) using Conda.

**Comment by KristapsE** [comment]
It seems to not like the AT1_.sdf - does it exist? Does it contain valid sdf data?
You could also try and provide the full set of diastereomers manually - ie AT1_1, AT1_2 etc and see if that works. This would mean the diastereomer generation would be skipped.

**Comment by L3ul** [comment]
I'm using data from this repository :
https://www.repository.cam.ac.uk/handle/1810/303161, AT1.zip/MM.

**Comment by KristapsE** [comment]
Have you tried opening the sdf file with a text editor to make sure it hasn't been corrupted by chance? Did you manage to run by giving the AT1_1.sdf, AT1_2.sdf files as inputs?

**Comment by ccyx1997** [comment]
I have came up with the same question in my win's system. It just because that at GetInchi in InchiGen.py at 165, the function used the path of current work path to find the NMR file. So you must put the AT1_.sdf at the same path with PyDP4.py

**Comment by KristapsE** [comment]
Oh, yes, thank you ccyx1997, that seems to be a peculiarity of the current GUI implementation. Something to add to the TO DO list then. The command line version shouldn't have this issue.

**Comment by L3ul** [comment]
ccyx1997's solution works. Cheers!

**Comment by KristapsE** [comment]
The latest update should have fixed the requirement to have the files in the source folder, allowing far more freedom in file locations.
